"""
Analyses the distribution of Sobol' indices.
"""

import openturns as ot


class SensitivityDistribution:
    """
    Checks the distribution of the sensitivity indices estimators.

    We compare the asymptotic distribution with an empirical sample of Sobol'
    indices estimates.

    We want to check that the distribution computed by the library is OK.
    When we estimate this distribution depending on the asymptotic estimator,
    this distribution is Gaussian.
    Otherwise, it is computed using kernel smoothing based on bootstrap.
    A first significant point is the mean of the distribution.
    The second significant point is the variance of the distribution, which
    is computed using the Delta-method when the asymptotic distribution is
    used.

    The reference distribution is computed based on a sample of Sobol' indices,
    which is generated by repetition.
    Then we compare the "Sample" distribution (from repetition) and the
    "Computed" distribution from the library.
    These two distributions should be close.
    """

    def __init__(
        self,
        problem,
        metaSAAlgorithm,
        sampleSize,
        numberOfRepetitions=10,
        estimator="Saltelli",
        samplingMethod="MonteCarlo",
    ):
        """
        Checks the distribution of the Sobol' estimator.

        Caution: This changes the "SobolIndicesExperiment-SamplingMethod"
        resource, which is used by the sampling estimators.

        Parameters
        ----------
        problem : ot.SensitivityBenchmarkProblem
            The problem.
        metaSAAlgorithm : SensitivityBenchmarkMetaAlgorithm
            A meta-sensitivity algorithm.
        sampleSize : int, optional
            The sample size.
        numberOfRepetitions : int, optional
            The number of times the estimation is repeated. The default is 10.
        estimator : str
            The estimator.
            Must be "Saltelli", "Jansen", "Martinez", "MauntzKucherenko".
        samplingMethod : str
            The sampling method.
            Must be "MonteCarlo" or "LHS" or "QMC".

        Returns
        -------
        None.

        """

        self.problem = problem
        self.metaSAAlgorithm = metaSAAlgorithm
        self.sampleSize = sampleSize
        self.numberOfRepetitions = numberOfRepetitions
        self.validEstimators = {
            "Saltelli",
            "Jansen",
            "Martinez",
            "MauntzKucherenko",
        }
        if estimator not in self.validEstimators:
            raise ValueError("Unknown value of estimator %s" % (estimator))
        self.estimator = estimator
        self.validSamplingMethods = {"MonteCarlo", "LHS", "QMC"}
        if samplingMethod not in self.validSamplingMethods:
            raise ValueError("Unknown value of sampling method : %s" % (samplingMethod))
        self.samplingMethod = samplingMethod
        ot.ResourceMap.SetAsString(
            "SobolIndicesExperiment-SamplingMethod", self.samplingMethod
        )

    def computeSampleIndices(self):
        """
        Generate a sample of first order and total order Sobol' indices.

        Returns
        -------
        sampleFirst : ot.Sample(numberOfRepetitions, dimension)
            A sample of first order Sobol' indices.
        sampleTotal : ot.Sample(numberOfRepetitions, dimension)
            A sample of total order Sobol' indices.
        distributionFirst : ot.Distribution
            The distribution of the first order Sobol' indices..
        distributionTotal : ot.Distribution
            The distribution of the total order Sobol' indices..
        """

        distribution = self.problem.getInputDistribution()
        dimension = distribution.getDimension()
        model = self.problem.getFunction()
        sampleFirst = ot.Sample(self.numberOfRepetitions, dimension)
        sampleTotal = ot.Sample(self.numberOfRepetitions, dimension)

        experiment = ot.SobolIndicesExperiment(distribution, self.sampleSize)

        isFirstSimulation = True

        for i in range(self.numberOfRepetitions):
            inputDesign = experiment.generate()
            outputDesign = model(inputDesign)
            if self.estimator == "Saltelli":
                sobolAlgorithm = ot.SaltelliSensitivityAlgorithm()
            elif self.estimator == "Jansen":
                sobolAlgorithm = ot.JansenSensitivityAlgorithm()
            elif self.estimator == "Martinez":
                sobolAlgorithm = ot.MartinezSensitivityAlgorithm()
            elif self.estimator == "MauntzKucherenko":
                sobolAlgorithm = ot.MauntzKucherenkoSensitivityAlgorithm()
            else:
                raise ValueError("Unknown value of estimator %s" % (self.estimator))
            sobolAlgorithm.setDesign(inputDesign, outputDesign, self.sampleSize)
            sampleFirst[i] = sobolAlgorithm.getFirstOrderIndices()
            sampleTotal[i] = sobolAlgorithm.getTotalOrderIndices()

            # Get the distribution
            if isFirstSimulation:
                distributionFirst = sobolAlgorithm.getFirstOrderIndicesDistribution()
                distributionTotal = sobolAlgorithm.getTotalOrderIndicesDistribution()
                isFirstSimulation = False

        return (
            sampleFirst,
            sampleTotal,
            distributionFirst,
            distributionTotal,
        )

    def draw(
        self,
    ):
        """
        Plot the distribution of the estimator and the distribution of the indices.

        Returns
        -------
        None.

        """
        (
            sampleFirst,
            sampleTotal,
            distributionFirst,
            distributionTotal,
        ) = self.computeSampleIndices()
        distribution = self.problem.getInputDistribution()
        dimension = distribution.getDimension()
        grid = ot.GridLayout(2, dimension)
        exactFirstOrder = self.problem.getFirstOrderIndices()
        exactTotalOrder = self.problem.getTotalOrderIndices()

        # For each estimator, compare the distribution and the sample distribution
        for marginalIndex in range(dimension):
            for firstOrderSobolEstimator in [True, False]:
                if firstOrderSobolEstimator:
                    label = f"$S_{{{marginalIndex}}}$"
                else:
                    label = f"$T_{{{marginalIndex}}}$"
                graph = ot.Graph("", label, "PDF", True, "topright")
                # Distribution of estimator
                if firstOrderSobolEstimator:
                    sampleJ = sampleFirst[:, marginalIndex]
                else:
                    sampleJ = sampleTotal[:, marginalIndex]
                sampleDistribution = ot.KernelSmoothing().build(sampleJ)
                curve = sampleDistribution.drawPDF()
                curve.setLegends(["Sample"])
                graph.add(curve)
                # Distribution computed by estimator
                if firstOrderSobolEstimator:
                    marginalDistribution = distributionFirst.getMarginal(marginalIndex)
                else:
                    marginalDistribution = distributionTotal.getMarginal(marginalIndex)
                curve = marginalDistribution.drawPDF()
                curve.setLegends(["Computed"])
                graph.add(curve)
                # Plot exact Sobol' index on the X axis
                if firstOrderSobolEstimator:
                    data = exactFirstOrder[marginalIndex]
                else:
                    data = exactTotalOrder[marginalIndex]
                cloud = ot.Cloud([[data]], [[0.0]])
                cloud.setLegend("Exact")
                graph.add(cloud)
                # Graphics options
                graph.setColors(ot.DrawableImplementation.BuildDefaultPalette(3))
                if firstOrderSobolEstimator:
                    rowIndex = 0
                else:
                    rowIndex = 1
                grid.setGraph(rowIndex, marginalIndex, graph)
        return grid
